export  const initialLeads: LeadCardProps[] = [
  {
    id: 1,
    isSelected: false,
    name: "User",
    email: "user@email.com",
    contact: "1234567890",
    lead_type: "s",
    assigned_to: "hero",
    priority: "cold",
    source: "4",
    status: 1,
    brokerage: null,
    created_dt: null,
    follow_up_current_status: null,
    golden: null,
    hash_key: "hash1",
    interested_in: null,
    last_updated_dt: "2023-08-24",
    product_code: null,
    product_type: null,
    query: null,
    recieved_date: null,
    revenue: null,
    sess_id: 1,
    source_assigned: null,
  },
  {
    id: 2,
    isSelected: false,
    name: "User",
    email: "user@email.com",
    contact: "1234567890",
    lead_type: "s",
    assigned_to: "hero",
    priority: "cold",
    source: "4",
    status: 1,
    brokerage: null,
    created_dt: null,
    follow_up_current_status: null,
    golden: null,
    hash_key: "hash2",
    interested_in: null,
    last_updated_dt: "2023-08-24",
    product_code: null,
    product_type: null,
    query: null,
    recieved_date: null,
    revenue: null,
    sess_id: 2,
    source_assigned: null,
  },
  {
    id: 3,
    isSelected: false,
    name: "User",
    email: "user@email.com",
    contact: "1234567890",
    lead_type: "s",
    assigned_to: "hero",
    priority: "cold",
    source: "4",
    status: 1,
    brokerage: null,
    created_dt: null,
    follow_up_current_status: null,
    golden: null,
    hash_key: "hash3",
    interested_in: null,
    last_updated_dt: "2023-08-24",
    product_code: null,
    product_type: null,
    query: null,
    recieved_date: null,
    revenue: null,
    sess_id: 3,
    source_assigned: null,
  },
]