export const sampleData = [
  {
    userId: 42,
    first_name: "Gaurav",
    last_name: "J",
    username: 'gj',
    mobile: "+91 1234567890",
    email: "user@example.com",
    manager: "Avinash J",
    department: "IT",
    status: "active",
    supervisor: "A",
  },
  {
    userId: 43,
    first_name: "Subrath",
    last_name: "Nayak",
    username: 'agentBinod',
    mobile: "+91 1234567890",
    email: "user@example.com",
    manager: "Avinash J",
    department: "IT",
    status: "inactive",
    supervisor: "A",
  },
]
