import { Employee } from "@/components/account/feature/employeeColumn"

export const employeeData: Employee[] = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    status: "active" as const,
    teamId: 1,
    role: "Software Developer",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "234-567-8901",
    status: "inactive" as const,
    teamId: 1,
    role: "Software Developer",
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice@example.com",
    phone: "345-678-9012",
    status: "active" as const,
    teamId: 1,
    role: "Software Developer",
  },
  {
    id: 4,
    name: "Bob Brown",
    email: "bob@example.com",
    phone: "456-789-0123",
    status: "inactive" as const,
    teamId: 1,
    role: "Software Developer",
  },
  {
    id: 5,
    name: "Charlie Black",
    email: "charlie@example.com",
    phone: "567-890-1234",
    status: "active" as const,
    teamId: 1,
    role: "Software Developer",
  },
]

export const additionalEmployeesData: Employee[] = [
  {
    id: 6,
    name: "Eve Williams",
    email: "eve.williams@example.com",
    phone: "678-901-2345",
    status: "active" as const,
    teamId: 2,
    role: "UI/UX Designer",
  },
  {
    id: 7,
    name: "Frank Harris",
    email: "frank.harris@example.com",
    phone: "789-012-3456",
    status: "inactive" as const,
    teamId: 2,
    role: "Project Manager",
  },
  {
    id: 8,
    name: "Grace Lee",
    email: "grace.lee@example.com",
    phone: "890-123-4567",
    status: "active" as const,
    teamId: 3,
    role: "Quality Assurance",
  },
  {
    id: 9,
    name: "Henry Walker",
    email: "henry.walker@example.com",
    phone: "901-234-5678",
    status: "inactive" as const,
    teamId: 3,
    role: "DevOps Engineer",
  },
  {
    id: 10,
    name: "Isabella Young",
    email: "isabella.young@example.com",
    phone: "012-345-6789",
    status: "active" as const,
    teamId: 4,
    role: "Product Owner",
  },
]
