export const featuresData = [
  { name: "Area", value: "2500 sqft" },
  { name: "Bedrooms", value: "3" },
  { name: "Bathrooms", value: "2" },
  { name: "Parking", value: "1 Garage" },
  { name: "Year Built", value: "2015" },
  { name: "Furnishing", value: "Semi-Furnished" },
  { name: "Balconies", value: "2" },
  { name: "Floor", value: "5th out of 10" },
  { name: "Power Backup", value: "24/7" },
  { name: "Gym", value: "Fully Equipped" },
  { name: "Swimming Pool", value: "Yes" },
  { name: "Security", value: "24/7 CCTV Surveillance" },
  { name: "Clubhouse", value: "Included" },
  { name: "Elevators", value: "3" },
]
