export const vendors = [
  {
    id: "1",
    vendorName: "Basware",
    logo: "/contracts/images/basware.svg",
    email: "contact@basware.com",
    website: "https://www.basware.com/en-us",
    description:
      "Track spending on assets within your purchase-to-pay process. Costs and warranty information are collected in your e-procurement system. Helps you conduct life cycle value comparisons, track which assets are on warranties and service contracts, properly depreciate fixed assets and get the most useful life from your equipment. Identify bulk ordering opportunities and avoid spending money on items you already have in stock, while ensuring critical items are on-hand.",
    vendorLocation: "Global",
    vendorServices: "Procurement",
    vendorMatchPercentage: 85,
    isVerified: true,
    regions: [1, 4],
    capabilities: [1, 2, 3],
    organizationalFunctions: [2, 4],
    contractTypes: [1, 5],
    licensingModels: [1],
    integrations: [1, 3],
  },
  {
    id: "2",
    vendorName: "Jaggaer",
    logo: "/contracts/images/Jaggaer-Logo-Red.svg",
    email: "gholt@jaggaer.com",
    website: "https://www.jaggaer.com",
    description:
      "JAGGAER enables organizations to consolidate and control all source-to-pay activities on JAGGAER ONE: a single, unified platform that transforms spend management into value creation. Offers end-to-end contract lifecycle management and supplier management.",
    vendorLocation: "Global",
    vendorServices: "Spend Management, Procurement",
    vendorMatchPercentage: 95,
    isVerified: true,
    regions: [1, 3, 4],
    capabilities: [1, 2, 5],
    organizationalFunctions: [1, 3],
    contractTypes: [1, 3, 5],
    licensingModels: [1, 3],
    integrations: [2, 4],
  },
  {
    id: "3",
    vendorName: "Cobblestone Systems",
    logo: "/contracts/images/cobblestone.svg",
    email: "sales@cobblestonesoftware.com",
    website: "https://www.cobblestonesystems.com/",
    description:
      "Contract Insight Enterprise is a robust system offering full contract lifecycle management, tracking, authoring with merging fields, dynamic clauses, approval and eSignature capabilities. It's designed to reduce contract expenses and increase governance.",
    vendorLocation: "Global",
    vendorServices: "Contract Management",
    vendorMatchPercentage: 90,
    isVerified: true,
    regions: [1, 4],
    capabilities: [1, 2, 4],
    organizationalFunctions: [2, 4, 5],
    contractTypes: [1, 4],
    licensingModels: [1, 2],
    integrations: [1, 3],
  },
  {
    id: "4",
    vendorName: "CallidusCloud",
    logo: "/contracts/images/calliduscloud.svg",
    email: "contact@calliduscloud.com",
    website:
      "https://www.sap.com/products/acquired-brands/what-is-calliduscloud.html",
    description:
      "CallidusCloud provides a complete suite of sales solutions that includes contract automation, repository creation, secure redlining of contracts, and milestone tracking.",
    vendorLocation: "Global",
    vendorServices: "Sales Automation",
    vendorMatchPercentage: 88,
    isVerified: true,
    regions: [1, 2, 3],
    capabilities: [1, 3, 4],
    organizationalFunctions: [2, 5],
    contractTypes: [1, 2],
    licensingModels: [1],
    integrations: [1, 3],
  },
  {
    id: "5",
    vendorName: "Navantis",
    logo: "/contracts/images/navantis.svg",
    email: "info@navantis.com",
    website: "https://www.navantis.com/",
    description:
      "Navantis offers Dolphin contract manager, which provides contract creation, repository, and integrated services for tracking and managing contract lifecycles.",
    vendorLocation: "Global",
    vendorServices: "Contract Management, Procurement",
    vendorMatchPercentage: 80,
    isVerified: true,
    regions: [1, 2],
    capabilities: [5, 6],
    organizationalFunctions: [2, 4],
    contractTypes: [1, 4],
    licensingModels: [1, 5],
    integrations: [2, 4],
  },
  {
    id: "6",
    vendorName: "Blue Ridge Software (DBA Contract Assistant)",
    logo: "/contracts/images/blueridge.svg",
    email: "support@contractassistant.com",
    website: "http://contractassistant.com/",
    description:
      "Contract Assistant provides contract management solutions with Standard, Pro, and Enterprise editions for organizations of all sizes, offering a scalable contract repository with customizable fields, advanced alerts, and full-text search capabilities.",
    vendorLocation: "Global",
    vendorServices: "Contract Management",
    vendorMatchPercentage: 75,
    isVerified: false,
    regions: [1, 4],
    capabilities: [4, 7],
    organizationalFunctions: [2, 5],
    contractTypes: [1, 3],
    licensingModels: [1, 3],
    integrations: [1, 2],
  },
  {
    id: "7",
    vendorName: "Gimmal",
    logo: "/contracts/images/gimmal.svg",
    email: "contact@gimmal.com",
    website: "https://gimmal.com/",
    description:
      "Gimmal provides contract management solutions with integration capabilities and a centralized repository. Offers advanced features like obligation tracking, automated alerts, and collaboration tools.",
    vendorLocation: "Global",
    vendorServices: "Contract Management, Procurement",
    vendorMatchPercentage: 78,
    isVerified: true,
    regions: [1, 2, 3],
    capabilities: [5, 6, 7],
    organizationalFunctions: [2, 4],
    contractTypes: [1, 5],
    licensingModels: [1, 2],
    integrations: [2, 4],
  },
  {
    id: "8",
    vendorName: "Contract Logix",
    logo: "/contracts/images/contractlogix.svg",
    email: "support@contractlogix.com",
    website: "https://www.contractlogix.com/",
    description:
      "Contract Logix offers Express, Professional, and Enterprise CLM platforms, providing contract repository solutions with optional contract authoring, built-in obligation notifications, and e-signature integration.",
    vendorLocation: "Global",
    vendorServices: "Contract Management",
    vendorMatchPercentage: 82,
    isVerified: true,
    regions: [1, 2, 4],
    capabilities: [2, 4, 6],
    organizationalFunctions: [2, 4],
    contractTypes: [1, 3],
    licensingModels: [1, 2],
    integrations: [1, 3],
  },
  {
    id: "9",
    vendorName: "Convergepoint",
    logo: "/contracts/images/convergepoint.svg",
    email: "info@convergepoint.com",
    website: "https://www.convergepoint.com/contract-management-software",
    description:
      "Convergepoint offers contract lifecycle management software with features like contract creation, obligation tracking, and advanced contract repository integration. It supports third-party integrations and tailored solutions for various industries.",
    vendorLocation: "Global",
    vendorServices: "Contract Management, Procurement",
    vendorMatchPercentage: 77,
    isVerified: false,
    regions: [1, 4],
    capabilities: [3, 6],
    organizationalFunctions: [2, 5],
    contractTypes: [1, 4, 5],
    licensingModels: [3, 5],
    integrations: [1, 4],
  },
  {
    id: "10",
    vendorName: "ContractPod Ai",
    logo: "/contracts/images/contractpodai.svg",
    email: "info@contractpodai.com",
    website: "https://contractpodai.com/",
    description:
      "ContractPod Ai offers a suite of contract lifecycle management tools with AI-driven contract analysis, customizable templates, built-in negotiation portals, and integration with Microsoft Azure for secure hosting.",
    vendorLocation: "Global",
    vendorServices: "Contract Management, AI Tools",
    vendorMatchPercentage: 85,
    isVerified: true,
    regions: [1, 2, 3],
    capabilities: [1, 3, 5],
    organizationalFunctions: [1, 2, 5],
    contractTypes: [1, 5],
    licensingModels: [1, 3, 5],
    integrations: [1, 2, 3],
  },
]

export const regions = [
  { id: 1, name: "APAC" },
  { id: 2, name: "EMEA" },
  { id: 3, name: "LatAm" },
  { id: 4, name: "North America" },
]

export const capabilities = [
  { id: 1, name: "Change Management" },
  { id: 2, name: "Configurable Approval Workflows" },
  { id: 3, name: "AI Built in" },
  { id: 4, name: "Version Comparison Redlining & Negotiation" },
  { id: 5, name: "Repository and Integration Capabilities" },
  { id: 6, name: "Custom Reporting and Queries" },
  { id: 7, name: "Obligation Tracking and Upload of Evidence" },
]

export const organizationalFunctions = [
  { id: 1, name: "Commercial" },
  { id: 2, name: "Legal" },
  { id: 3, name: "Other Dept" },
  { id: 4, name: "Procurement" },
  { id: 5, name: "Risk/Compliance" },
]

export const contractTypes = [
  { id: 1, name: "Buy Side" },
  { id: 2, name: "Distribution" },
  { id: 3, name: "Employment" },
  { id: 4, name: "Other Type" },
  { id: 5, name: "Sell Side" },
]

export const licensingModels = [
  { id: 1, name: "Annual subscription fee" },
  { id: 2, name: "Annual subscription fee with maintenance" },
  { id: 3, name: "Monthly subscription fee" },
  { id: 4, name: "Perpetual" },
  { id: 5, name: "Volume-based" },
]

export const integrations = [
  { id: 1, name: "Application Integration (API)" },
  { id: 2, name: "E-mail Client" },
  { id: 3, name: "eSignatures" },
  { id: 4, name: "Financials and Supply Chain Management (FSCM)" },
]
